### PR TITLE
Listen for chat message

### PR DESCRIPTION
**Pull request by HonbraDev**
Added a simple function to listen for chat messages.

### CODE REVIEW

**Comment by jamesql** [comment]
very cool poggers contribution very pog do you work at faang?

**Comment by HonbraDev** [comment]
No, but thanks.

**Comment by jamesql** [comment]
real note, very good contribution +like

**Comment by xkral-tr** [comment]
?

**Comment by HonbraDev** [comment]
ØH MŸ GŌĎ Į ÇÒMMÎŤŤËĎ HÓŁŸ ČŔÄP

**Review by JackCrispy — APPROVED** [review]

**Comment by JackTGG** [comment]
nice

**Pull request merged**
